[package]
name = "all-optimizations"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
dioxus = { workspace = true }
dioxus-web = { workspace = true }
im-rc = { workspace = true }