[workspace]
resolver = "2"
members = ["no-optimizations", "stable-optimizations", "all-optimizations"]

[workspace.dependencies]
dioxus = "0.4.0"
dioxus-web = "0.4.0"
im-rc = "15.1.0"

[workspace.package]
version = "0.1.0"
edition = "2021"