name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v1

      - name: Install CLI
        run: cargo install dioxus-cli --locked

      - name: Dioxus build
        run: |
          dx build --release --bin no-optimizations
          dx build --release --bin stable-optimizations
          dx build --release --bin all-optimizations